# Global configuration file (/etc/rtaspi/config.yaml)
# This file contains system-wide settings

system:
  storage_path: /var/lib/rtaspi/storage
  log_level: INFO

web:
  enable: true
  host: 0.0.0.0
  port: 8000
  enable_https: false

streaming:
  rtsp:
    port_start: 8554
    enable_auth: true
    auth_method: basic
  rtmp:
    port_start: 1935
    enable_auth: true
  webrtc:
    port_start: 8080
    stun_server: stun://stun.l.google.com:19302

processing:
  video:
    default_resolution: 1280x720
    default_fps: 30
    default_format: h264
  audio:
    default_sample_rate: 44100
    default_channels: 2
    default_format: aac
