server:
  host: 0.0.0.0
  port: 8443
  ssl:
    cert: certs/server.crt
    key: certs/server.key
  cors:
    origins: ["*"]
    methods: ["GET", "POST"]

auth:
  type: jwt
  secret: ${JWT_SECRET}
  expiry: 3600

rate_limit:
  requests: 100
  window: 60
